project:
  type: website

website:
  title: "Andre E. Kim"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Blog
    tools:
      - icon: github
        href: https://github.com/dre2k/dre2k.github.io
    background: dark

format:
  html:
    theme: yeti
    css: styles.css
    toc: false